# Generated by Django 5.1 on 2024-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='titulo',
            field=models.CharField(default='Sem Titulo', max_length=30),
            preserve_default=False,
        ),
    ]
